# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'asd' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

	pod 'FirebaseCore'
  pod 'Firebase/Firestore', '~> 6.23.0'
  
  pod 'FirebaseFirestoreSwift', :podspec => 'https://raw.githubusercontent.com/firebase/firebase-ios-sdk/master/FirebaseFirestoreSwift.podspec'
  
  pod 'SDWebImage'
  
  pod 'Firebase/Database'

  # Pods for asd

end
